<?php
//{{ __('Message') }}
//{{ __('frontlang.about_employer', ['employer_name' => $employer->name_en]) }}

return [

    'Loading...' => 'Loading...', 
    
    // Header
    'Home' => 'Home',    
    'Categories' => 'Categories',
    'Cities' => 'Cities',    
    'Find Jobs' => 'Find Jobs',
    'Find Employers' => 'Find Employers',    
    'Employer' => 'Employer',
    'Job Seeker' => 'Job Seeker',
    'Cookie Policy' => 'Cookie Policy',
    'currently working' => 'currently working',
    
    'Dashboard' => 'Dashboard',
        'My Job Applications' => 'My Job Applications',
        'My Favourite Jobs' => 'My Favourite Jobs',
        'My Job Offers' => 'My Job Offers', 
        'My Open Offers' => 'My Open Offers',    
        'My Active Jobs' => 'My Active Jobs',
        'Inbox' => 'Inbox',    
        'My inbox' => 'My inbox',
        'Notifications' => 'Notifications', 
        'My Notifications' => 'My Notifications',
        'Read All' => 'Read All',   
        'Profile' => 'Profile',    
        'Edit profile' => 'Edit profile',
        'Change Password' => 'Change Password',
        'Logout' => 'Logout',
        'Matching Jobs' => 'Matching Jobs', 
    
    // Sign in as Job Seeker modal
    'Sign in' => 'Sign in',  
    'Welcome back!' => 'Welcome back!',
    'Email address' => 'Email Address',
    'Password' => 'Password',
    'Login with Facebook' => 'Login with Facebook',
    'Login with Google' => 'Login with Google',
    'New to' => 'New to',  
    
    // Sign up as Job Seeker modal
    'Sign up' => 'Sign up',
    'Sign up as Job Seeker' => 'Sign up as Job Seeker',
    'Full Name' => 'Full Name',
    'Phone Number' => 'Phone Number',
    'Your password' => 'Your password',
    'Already have an Account? Sign in' => 'Already have an Account? Sign in',
    
    // Forgot password modal
    'Forgot password' => 'Forgot Password',
    'Continue' => 'Continue',
    
    // Sign up as Employer modal
    'Sign up as Employer' => 'Sign up as Employer',
    'Employer/Company Name' => 'Employer/Company Name',
    'Manager Name' => 'Manager Name',
    
    
    // Apply Job Modal
    'Are You Sure You want To Apply For this Job?' => 'Are You Sure You want To Apply For this Job?',
    'Apply' => 'Apply',    
    'Yes' => 'Yes',        
    'No' => 'No',    
    'You can not Apply, Your Profile is not Complete. Please Complete Your Profile' => 'You can not Apply, Your Profile is not Complete. Please Complete Your Profile',
    'Click On the following Link' => 'Click On the following Link',    
    'Applied' => 'Applied',

    // Ajax Response From Controller
    'Your have Successfully Applied to the Job.' => 'Your have Successfully Applied to the Job.',
    'This job has been removed from your job appications.' => 'This job has been removed from your job appications.',
    'Employer already declined your application for this job.' => 'Employer already declined your application for this job.',
    'Employer already accepted your application for this job.' => 'Employer already accepted your application for this job.',
    'Job Offer has been declined for this job.' => 'Job Offer has been declined for this job.',
    'You have already accepted an offer for this job.' => 'You have already accepted an offer for this job.',
    'Zaphri: Job Application Received' => 'Zaphri: Job Application Received',
    'Zaphri: Job Offer Accepted' => 'Zaphri: Job Offer Accepted',
    'Job Offer Accepted.' => 'Job Offer Accepted.',
    'Record Not Found.' => 'Record Not Found.',
    'Zaphri: Job Offer Declined' => 'Zaphri: Job Offer Declined',
    'Job Offer Declined.' => 'Job Offer Declined.',
    'Open Offer Declined' => 'Open Offer Declined',
    'Zaphri: Open Offer Declined' => 'Zaphri: Open Offer Declined',
    'Please add some message to send.' => 'Please add some message to send.',
    'Please select valid profile.' => 'Please select valid profile.',
    'No Email address added in the profile.' => 'No Email address added in the profile.',
    'Laravel Test Mail' => 'Laravel Test Mail',
    'Please select valid profile.' => 'Please select valid profile.',
    'Your Message Successfully Sent' => 'Your Message Successfully Sent',
    'No Phone Number added in the profile.' => 'No Phone Number added in the profile.',
    'Your SMS Successfully Sent' => 'Your SMS Successfully Sent',
    'Email Successfully Sent' => 'Email Successfully Sent',
    'Job Has Been Reported' => 'Job Has Been Reported',
    'Please add some comments.' => 'Please add some comments.',
    'Job Has Been Rated' => 'Job Has Been Rated',


    
    // Jquery Validation Messages
    'Please Enter Name' => 'Please enter Name',
    'Please Enter Phone' => 'Please enter Phone',
    'Please Enter Email' => 'Please enter Email Address',
    'Please Enter Valid Email' => 'Please enter valid Email Address',
    'Please Enter password' => 'Please enter Password',
    
    // Footer
    'Call us' => 'Call us',
    
    'Quick Links' => 'Quick Links',    
        'About Us' => 'About Us',
        'Contact Us' => 'Contact Us',   
        'Terms & Conditions' => 'Terms & Conditions',
        'Privacy Policy' => 'Privacy Policy',   
        'FAQs' => 'FAQs',
    
    'For Candidates' => 'For Candidates',
        'Candidate Dashboard' => 'Candidate Dashboard',
    
    'For Employers' => 'For Employers',
        'Find Candidates' => 'Find Candidates',
        'Company Dashboard' => 'Company Dashboard',
        'Post a Job' => 'Post a Job',
        'Manage Jobs' => 'Manage Jobs',
        'Candidates' => 'Candidates',    
    
    'All Right Reserved.' => 'All Right Reserved.',
    'Made with' => 'Made with',    
        'in' => 'in',    
        'canada' => 'Canada', 
    
    'No records Found' => 'No Records Found',
    'Showing' => 'Showing',    
    'pagination_records' => ':firstRecord - :lastRecord of :totalRecords',
    'of' => 'of',    
    'Sort by' => 'Sort by',
    'Name Asc' => 'Name Asc',    
    'Name Desc' => 'Name Desc',
    'Latest' => 'Latest',
    'Oldest' => 'Oldest',
    'open_positions' => ':count Open Positions', 
    'employer_jobs' => ':count Jobs', 
    
    
    'by' => 'by', 
    'in' => 'in',    
    
    
    // Categories Listing page
    'Search by Category' => 'Search by Category EN',    
    'Search your career opportunity with our categories' => 'Search your career opportunity with our Categories',
    'Category Name or Keyword' => 'Category Name or Keyword',    
    'Find Category' => 'Find Categories',   
    'categories' => 'Categories',  
    
    
    // Sub Categories Listing page
    'Search by Sub Category' => 'Search by Sub Category',    
    'Search your career opportunity with our sub categories' => 'Search your career opportunity with our Sub Categories',
    'Sub Category Name or Keyword' => 'Sub Category Name or Keyword',      
    'All Categories' => 'All Categories',  
    'Find SubCategory' => 'Find SubCategories',   
    'sub categories' => 'Sub Categories',  
    
    
    // Employers Listing page
    'Search by Employer' => 'Search by Employer',    
    'Search your career opportunity with our employers' => 'Search your career opportunity with our Employers',
    'Employer Name or Keyword' => 'Employer Name or Keyword',
    'Find Employers' => 'Find Employers',   
    'employers' => 'Employers',
    
    // Employer Details page 
    'about_employer' => 'About :employer_name', 
    'Benefits' => 'Benefits',    
    'Social Links' => 'Social Links',
    'Website' => 'Website',    
    'Location' => 'Location',
    'Phone' => 'Phone',    
    'Email' => 'Email',    
    'Contact Employer' => 'Contact Employer',    
    'Message' => 'Message',    
    'Type your message here...' => 'Type your message here...',
    'Send Message' => 'Send Message',
    'Available Jobs' => 'Available Jobs',    
    'latest_jobs_by_employer' => 'Latest Jobs posted by :employer_name',
    
    
    // Cities Listing page
    'Search by City' => 'Search by City',    
    'Search your career opportunity with our cities' => 'Search your career opportunity with our Cities',
    'City Name or Keyword' => 'City Name or Keyword',    
    'Find City' => 'Find Cities',   
    'All Provinces/Territories' => 'All Provinces/Territories',   
    'cities' => 'Cities', 
     
    
    
    // Jobs Listing page
    'Search Jobs' => 'Search Jobs',    
    'Search your career opportunity through our listed jobs' => 'Search your career opportunity through our listed jobs',
    'Job Title or Keyword' => 'Job Title or Keyword',
    'All Locations' => 'All Locations',
    'Matching Profile Jobs' => 'Matching Profile Jobs',
    'Find Matching Jobs' => 'Find Matching Jobs',    
    'Filter Jobs' => 'Filter Jobs',
    'Employement Periods' => 'Employement Periods',
    'Employement Groups' => 'Employement Groups',
    'Ethnicities' => 'Ethnicities',    
    'Employement Conditions' => 'Employement Conditions',
    'Employement Benefits' => 'Employement Benefits',
    'Hours of Work' => 'Hours of Work',    
    'Languages at Work' => 'Languages at Work',
    'jobs' => 'Jobs',
    'List View' => 'List View',    
    'Map View' => 'Map View',
    'Please wait! Map is Loading...' => 'Please wait! Map is Loading...',
    'More Filters' => 'More Filters',
    'Jobs on Map' => 'Jobs on Map',
    'Show' => 'Show',
    'Hide' => 'Hide',
    'Filters Jobs' => 'Filters Jobs',
    'filter your career opportunity through your skill match jobs' => 'filter your career opportunity through your skill match jobs',
    'Filter By Skill' => 'Filter By Skill',

    // Home page 
    'Featured Job Offers' => 'Featured Job Offers',
    'Search your career opportunity through 12,800 jobs' => 'Search your career opportunity through 12,800 jobs',
    'All Job Offers' => 'All Job Offers',
    'Find Best Companies' => 'Find Best Companies',
    'Work for the best companies in the world' => 'Work for the best companies in the world',
    'All Companies' => 'All Companies',
    'Featured Cities' => 'Featured Cities',
    'Start your next carrer in a beautiful city' => 'Start your next carrer in a beautiful city',
    'All Cities' => 'All Cities',
   
    
    // User Profile 
    'User details updated successfully.' => 'User details updated successfully.',
    'User not found. Please try again.' => 'User not found. Please try again.',
    'Please fill all required fields.' => 'Please fill all required fields.',
    'Record Already Exists with same User name' => 'Record Already Exists with same User name',
    'About' => 'About',
    'Skills' => 'Skills',
    'Trainings' => 'Trainings',
    'Certifications' => 'Certifications',
    'Work Experience' => 'Work Experience',
    'Education' => 'Education',
    'Emergency Contact' => 'Emergency Contact',
    'Employement Hours' => 'Employement Hours',
    'View as Public Profile' => 'View as Public Profile',
    'About You' => 'About You',
    'Expected Salary' => 'Expected Salary',
    'Interested In' => 'Interested In',
    'Documents' => 'Documents',
    'Edit Basic Profile' => 'Edit Basic Profile',
    'Upload Cover Image' => 'Upload Cover Image',
    'Upload' => 'Upload',
    'Photo' => 'Photo',
    'Name' => 'Name',
    'Heading' => 'Heading',
    'Address' => 'Address',
    'City' => 'City',
    'Salary Type' => 'Salary Type',
    'Interested in Employement Period' => 'Interested in Employement Period',
    'Interested in Employement Conditions' => 'Interested in Employement Conditions',
    'Interested in Employement Hours' => 'Interested in Employement Hours',
    'Languages' => 'Languages',
    'Type your info here...' => 'Type your info here...',
    'Edit Skills' => 'Edit Skills',
    'Add Skill' => 'Add Skill',
    'Add' => 'Add',
    'Document Type' => 'Document Type',
    'Expiry' => 'Expiry',
    'Document Status' => 'Document Status',
    'Actions' => 'Actions',
    'No Expiry Date' => 'No Expiry Date',
    'Uploaded' => 'Uploaded',
    'Not Uploaded' => 'Not Uploaded',
    'Upload Documents' => 'Upload Documents',
    'Cancel' => 'Cancel',
    'Edit Training' => 'Edit Training',
    'Add Training' => 'Add Training',
    'Title' => 'Title',
    'Institute/College/School' => 'Institute/College/School',
    'From' => 'From',
    'To' => 'To',
    'Edit Certification' => 'Edit Certification',
    'Add Certification' => 'Add Certification',
    'Issuing Authority' => 'Issuing Authority',
    'Issue Date' => 'Issue Date',
    'has expiry date' => 'has expiry date',
    'Expiry date' => 'Expiry date',
    'Edit Experience' => 'Edit Experience',
    'Add Experience' => 'Add Experience',
    'Job title' => 'Job title',
    'Company' => 'Company',
    'Responsibilities here...' => 'Responsibilities here...',
    'Edit Education' => 'Edit Education',
    'Educations' => 'Educations',
    'Add Education' => 'Add Education',
    'Edit Social Links' => 'Edit Social Links',
    'Update Education' => 'Update Education',
    'Description' => 'Description',
    'Update Training' => 'Update Training',
    'Update Certification' => 'Update Certification',
    'Edit' => 'Edit',
    'Delete' => 'Delete',
    'Documents uploaded successfully' => 'Documents uploaded successfully',
    'Social Links updated successfully.' => 'Social Links updated successfully.',
    'Skills updated successfully' => 'Skills updated successfully',
    'Education updated successfully' => 'Education updated successfully',
    'Experience updated successfully' => 'Experience updated successfully',
    'Trainings updated successfully' => 'Trainings updated successfully',
    'Certifications updated successfully' => 'Certifications updated successfully',
    'To Complete Profile Verify Email' => 'To Complete Profile Verify Email',
    'To Complete Your Profile Verify Phone' => 'To Complete Your Profile Verify Phone',
    'To Complete Profile Upload Photo' => 'To Complete Profile Upload Photo',
    'To Complete Profile Add Some Skill' => 'To Complete Profile Add Some Skill',
    'To Complete Profile Add Documents' => 'To Complete Profile Add Documents',
    'To Complete Profile Add Some Trainings' => 'To Complete Profile Add Some Trainings',
    'To Complete Profile Add Some Certifications' => 'To Complete Profile Add Some Certifications',
    'To Complete Profile Add Some Experiences' => 'To Complete Profile Add Some Experiences',
    'To Complete Profile Add Education' => 'To Complete Profile Add Education',
    'To Complete Profile Add Socials Links' => 'To Complete Profile Add Socials Links',
    'Thank You! Your Profile is completed' => 'Thank You! Your Profile is completed',
    
    
    // Job Details Page
    'Post Date' =>'Post Date',
    'Per Annual' => 'Per Annual',
    'Per Hour' => 'Per Hour',
    'Overview' => 'Overview',
    'Responsibilities' => 'Responsibilities',
    'Requirements' => 'Requirements',
    'For Groups' => 'For Groups',
    'Job Benefit' => 'Job Benefit',
    'Language at Work' => 'Language at Work',
    'Related Jobs' => 'Related Jobs',
    'Other similar jobs that might interest you' => 'Other similar jobs that might interest you',
    'No overview provided.' => 'No overview provided by company/publisher.',
    'No responsibilities provided.' => 'No responsibilities provided by company/publisher.',
    'No requirements provided.' => 'No requirements provided by company/publisher.',
     
     // Seeker Dashboard Job

    'Record Not Available' => 'Record Not Available',
    'No Favorite Job Available' => 'No Favorite Job Available',
    'No Applicant Available' => 'No Applicant Available',
    'No Offered Job Available' => 'No Offered Job Available',
    'No Active Job Available' => 'No Active Job Available',
    'Overview' => 'Overview',


    // Change Password
    'Choose a new account password' => 'Choose a new account password',
    'Old password' => 'Old password',
    'Enter old password' => 'Enter old password',
    'New password' => 'New password',
    'Enter new password' => 'Enter new password',
    'Confirm New password' => 'Confirm New password',
    'Repeat new password' => 'Repeat new password',
    'Save' => 'Save',
    'Delete' => 'Delete',
    'Password updated successfully' => 'Password updated successfully',




    'dashboard' => 'Dashboard',

    
    // Dashboard 
    'Dashboard' => 'Dashboard',
    'Welcome to' => 'Welcome to',
    'Job applications' => 'Job applications',
    'Favourite Jobs' => 'Favourite Jobs',
    'job Offers' => 'job Offers',
    'Active Jobs' => 'Active Jobs',
    'Latest Matching Jobs' => 'Latest Matching Jobs',
    'Recent Job Apllications' => 'Recent Job Apllications',
    'Email address has been successfully verified' => 'Email address has been successfully verified',


    // Job Application Listing
    'list of Applied Jobs' => 'list of Applied Jobs',
    'Are You Sure To cancel this Job Application?' => 'Are You Sure To cancel this Job Application?',

    // common
    'Show me more...' => 'Show me more...',
    'OverView' => 'OverView',
    'Map' => 'Map',
    'Sub Category' => 'Sub Category',
    'Category' => 'Category',
    'Positions' => 'Positions',
    'Created Date' => 'Created Date',
    'Modified Date' => 'Modified Date',
    'Provience' => 'Provience',
    'Eligibility' => 'Eligibility',
    'All' => 'All',
    'Accepted' => 'Accepted',
    'Declined' => 'Declined',
    'Close' => 'Close',
    'Are You Sure To Apply For Job' => 'Are You Sure To Apply For Job',
    'Offered' => 'Offered',
    'Accept Job offer' => 'Accept Job offer',
    'Accept' => 'Accept',
    'Decline Job offer' => 'Decline Job offer',
    'Decline' => 'Decline',
    'Accept Open offer' => 'Accept Open offer',
    'Short tags will be replaced by dynamic content.please do not remove' => 'Short tags will be replaced by dynamic content.please do not remove',
    'Decline Open offer' => 'Decline Open offer',
    'Review The Job' => 'Review The Job',
    'Review' => 'Review',
    'Report The Job' => 'Report The Job',
    'Report' => 'Report',

    // Favorite Job
    'list of Favorite Jobs' => 'list of Favorite Jobs',

    // Offer Job
    'list of Offered Jobs' => 'list of Offered Jobs',

    // Open Offer
    'list of Offered Jobs' => 'list of Offered Jobs',
    'No of days' => 'No of days',
    'Annual' => 'Annual',
    'Hour' => 'Hour',
    'Status' => 'Status',
    'Offer' => 'Offer',
    'Offered Salary' => 'Offered Salary',
    'Contacts' => 'Contacts',

    // Active Jobs
    'list of Active Jobs' => 'list of Active Jobs',

    // Notification
    'Notification' => 'Notification',
    'History of all your received notifications' => 'History of all your received notifications',
    'records' => 'records',
    'Notification Not Found' => 'Notification Not Found',
    'Job Not Found' => 'Job Not Found',
    'A Job Seeker has applied on your published Job' => 'A Job Seeker has applied on your published Job',
    'An applicant has withdrawn his Job Application' => 'An applicant has withdrawn his Job Application',
    'You have Shortlisted a Job Application' => 'You have Shortlisted a Job Application',
    'You have Declined a Job Application' => 'You have Declined a Job Application',
    'You have Approved a Job Application' => 'You have Approved a Job Application',
    'You have sent a Job Offer to a Job Seeker' => 'You have sent a Job Offer to a Job Seeker',
    'You have Cancelled a Job Offer' => 'You have Cancelled a Job Offer',
    'A Job Offer sent by you has been Accepted' => 'A Job Offer sent by you has been Accepted',
    'A Job Offer sent by you has been Declined' => 'A Job Offer sent by you has been Declined',
    'You have sent an Open Job Offer to a Job Seeker' => 'You have sent an Open Job Offer to a Job Seeker',
    'You have Cancelled an Open Job Offer' => 'You have Cancelled an Open Job Offer',
    'An Open Job Offer sent by you has been Accepted' => 'An Open Job Offer sent by you has been Accepted',
    'An Open Job Offer sent by you has been Declined' => 'An Open Job Offer sent by you has been Declined',
    'Your Document is Expired' => 'Your Document is Expired',
    'A Job Offer sent by you has been Expired' => 'A Job Offer sent by you has been Expired',
    'A Open Offer sent by you has been Expired' => 'A Open Offer sent by you has been Expired',
    'A Job you have Published has been Expired' => 'A Job you have Published has been Expired',
    'You have applied on a published Job' => 'You have applied on a published Job',
    'You have withdrawn your Job Application' => 'You have withdrawn your Job Application',
    'Employer Shortlisted your Job Application' => 'Employer Shortlisted your Job Application',
    'Employer Declined your Job Application' => 'Employer Declined your Job Application',
    'Employer Approved your Job Application' => 'Employer Approved your Job Application',
    'You have received a Job Offer from an Employer' => 'You have received a Job Offer from an Employer',
    'Job Offer received by an Employer have been Cancelled' => 'Job Offer received by an Employer have been Cancelled',
    'You have Accepted a Job Offer' => 'You have Accepted a Job Offer',
    'You have Declined a Job Offer' => 'You have Declined a Job Offer',
    'You have received an Open Job Offer from an Employer' => 'You have received an Open Job Offer from an Employer',
    'Open Job Offer received by an Employer have been Cancelled' => 'Open Job Offer received by an Employer have been Cancelled',
    'You have Accepted an Open Job Offer' => 'You have Accepted an Open Job Offer',
    'You have Declined an Open Job Offer' => 'You have Declined an Open Job Offer',
    'Job Offer received by an Employer have been Expired' => 'Job Offer received by an Employer have been Expired',
    'Open Offer received by an Employer have been Expired' => 'Open Offer received by an Employer have been Expired',

    // inbox
    'Keep in touch with companies' => 'Keep in touch with companies',
    'Check inbox' => 'Check inbox',
    'Click On Side Menu to Show Chat' => 'Click On Side Menu to Show Chat',
    'Type your message here...' => 'Type your message here...',
    'Send' => 'Send',


    // Button Helper Message 
    'Applied' => 'Applied',
    'Apply' => 'Apply',
    'Viewed' => 'Viewed',
    'Shortlisted' => 'Shortlisted',
    'Application Declined' => 'Application Declined',
    'Application Approved' => 'Application Approved',
    'Unknown' => 'Unknown',
    'Accept Offer' => 'Accept Offer',
    'Decline Offer' => 'Decline Offer',
    'Offer Declined' => 'Offer Declined',
    'Offer Accepted' => 'Offer Accepted',
    'Offer Expired' => 'Offer Expired',
    'Reports' => 'Reports',
    'Reviews' => 'Reviews',
    'Pending' => 'Pending',
    'Not Applied' => 'Not Applied',
    'Add New' => 'Add New',
    'Applied' => 'Applied',
    'Applied' => 'Applied',
    'Applied' => 'Applied',
    'Applied' => 'Applied',
    'Applied' => 'Applied',




    'toTop' => 'to Top',
    'AllRightsReserved' => 'All Rights Reserved',
    'moreDetails' => 'More Details',
    'viewMore' => 'View More',
    'readMore' => 'Read More',
    'downloadAttach' => 'Download Attachment',
    'contactDetails' => 'Contact Details',
    'callUs' => 'Call Us',
    'callFax' => 'Fax',
    'callMobile' => 'Mobile',
    'callPhone' => 'Phone',
    'callTimes' => 'Working Times',
    'address' => 'Address',
    'name' => 'Name',
    'email' => 'Email',
    'phone' => 'Phone',
    'latestNews' => 'Latest News',
    'ourGallery' => 'Our Gallery',
    'subscribeToOurNewsletter' => 'Subscribe To Our Newsletter',
    'subscribeToOurNewsletterDone' => 'You have Subscribed',
    'subscribeToOurNewsletterError' => 'You Already Subscribed',
    'newsletter' => 'Our Newsletter',
    'subscribe' => 'Subscribe',
    'yourEmail' => 'Your Email',
    'yourName' => 'Your Name',
    'enterYourName' => 'Please enter your name',
    'enterYourEmail' => 'Please enter your email address',
    'enterYourPhone' => 'Please enter your phone number',
    'enterYourSubject' => 'Please enter a subject for your message',
    'enterYourMessage' => 'Please type your message',
    'youMessageSent' => 'Your message has been sent successfully, We will contact you as soon as possible. Thank you!',
    'youMessageNotSent' => 'Error: Please try again',
    'subject' => 'Subject',
    'message' => 'Message',
    'sendMessage' => 'Send Message',
    'workingHours' => 'Working Hours',
    'noData' => 'There is no data here up to now',
    'mostViewed' => 'Most Viewed',
    'share' => 'Share',
    'locationMap' => 'Location Map',
    'comments' => 'Comments',
    'comment' => 'Comment',
    'enterYourComment' => 'Please enter your comment',
    'sendComment' => 'Send Comment',
    'youCommentSent' => 'Your Comment has been sent successfully. Thank you!',
    'newComment' => 'Add New Comment',
    'refresh' => 'Refresh',
    'getInTouch' => 'Get in touch with us by filling contact form below',
    'homeContents1Title' => 'Latest Articles',
    'homeContents1desc' => 'The latest articles from our blog, you can browse more',
    'homeContents2Title' => 'Recent Works',
    'homeContents2desc' => 'Some of our latest works, you can browse more',
    'search' => 'Search for...',
    'visits' => 'Visits',
    'orderForm' => 'Order form',
    'quantity' => 'Quantity',
    'yourQuantity' => 'Please enter quantity',
    'notes' => 'Notes',
    'sendOrder' => 'Send Order',
    'youOrderSent' => 'Your Order has been sent successfully. We will contact you as soon as possible.',

    'partners' => 'Our Partners',
    'partnersMsg' => 'Long term partnerships with leading local and international companies',
];

?>