<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GeneralTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('generals')->insert([
            [
                'reload_time' => 3,
                'support_email' => 'support@zaphri.com',
                'site_title' => 'Zaphri',
                'site_url' => 'https://www.zaphri.com/',
                'paypal' => 0,
                'paypal_account' => 'jutroxllc@gmail.com',
                'paypal_client_id' => 'AZQr4fvPiqRS8qColLb4RiRGSP-Q3aA2WixcXLNOQhTpo1Ngpp6innmMWKqsc9uekOfvxoYvbdlELYdo',
                'paypal_secret_key' => 'EFjM1V48JvABBbs74OWA8ewduIAP9VYfW3jL6hXDgNhF8Zg1dnNCB8MJ_D4sR-48aGlo2tDJLJemponn',
                
                'verify_subject' => 'Verify Your Email Address',
                'verify_email' => '<p><span style="font-weight: 700;">If you have signed up using&nbsp;</span><span style="font-weight: 700;">[SITENAME]&nbsp;</span><span style="font-weight: 700;">app, Kindly use code below to verify your email:</span></p><p>Verification Code for [Email] is [code]</p><p><span style="font-weight: 700;"><br></span></p><p><span style="font-weight: 700;">To complete your [SITENAME] sign up from Website, click the link below to verify your email address:&nbsp;</span><span style="font-weight: 700;">[Email]</span></p><p><span style="font-weight: 700;"><br></span></p><p>[Button: link to verify]</p><p><br></p><p>Above link not working? Paste the following link into your browser:<br></p><p>[text: link to verify]</p><p helvetica="" neue",="" helvetica,="" arial,="" sans-serif;"="" style="color: rgb(29, 34, 40);"><span style="font-size: 10pt; color: rgb(103, 106, 108);">&nbsp;</span><br></p><p></p><p style="margin: 0cm 0cm 7.5pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span segoe="" ",="" roboto,="" oxygen,="" ubuntu,="" "fira="" "droid="" "helvetica="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" "=""><span open="" sans",sans-serif;color:#172b4d"="" style="font-size: 10pt;">You are receiving this email because you recently created an account in the&nbsp;</span></span><span open="" sans",="" sans-serif;"="" style="font-size: 10pt;">[SITENAME]</span><span segoe="" ",="" roboto,="" oxygen,="" ubuntu,="" "fira="" "droid="" "helvetica="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" "=""><span open="" sans",sans-serif;color:#172b4d"="" style="font-size: 10pt;">&nbsp;registered with this email address. If this was not you, please ignore this email.</span></span></p>',
                
                'verification_subject' => 'Verification Code Send',
                'verification_email' => '<p><b>Verification code for your email [Email] : [code]</b></p><p><br><br><p>If this was not you, please ignore this email.</p>',
                
                'welcome_subject' => 'Welcome to [SITENAME]',
                'welcome_email' => '<p>Welcome [USERNAME],</p><p><span style="white-space:pre">						</span></p><p>Your [SITENAME] account has been created as a [USERTYPE].</p><p><br></p><p style="color: rgb(29, 34, 40); font-family: " helvetica="" neue",="" helvetica,="" arial,="" sans-serif;"="">Thank you for choosing <span style="color: rgb(103, 106, 108); font-family: " open="" sans",="" "helvetica="" neue",="" helvetica,="" arial,="" sans-serif;"="">[SITENAME]</span>!</p><p style="color: rgb(29, 34, 40); font-family: " helvetica="" neue",="" helvetica,="" arial,="" sans-serif;"="">-<br>The <span style="color: rgb(103, 106, 108); font-family: " open="" sans",="" "helvetica="" neue",="" helvetica,="" arial,="" sans-serif;"="">[SITENAME] </span>Team</p><p style="color: rgb(29, 34, 40); font-family: " helvetica="" neue",="" helvetica,="" arial,="" sans-serif;"=""><span style="font-size: 10pt; color: rgb(103, 106, 108);">&nbsp;</span><br></p><p></p><p style="margin: 0cm 0cm 7.5pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span segoe="" ",="" roboto,="" oxygen,="" ubuntu,="" "fira="" "droid="" "helvetica="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" "=""><span open="" sans",sans-serif;color:#172b4d"="" style="font-size: 10pt;">You are receiving this email because you recently created an account in the&nbsp;</span></span><span open="" sans",="" sans-serif;"="" style="font-size: 10pt;">[SITENAME]</span><span segoe="" ",="" roboto,="" oxygen,="" ubuntu,="" "fira="" "droid="" "helvetica="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" "=""><span open="" sans",sans-serif;color:#172b4d"="" style="font-size: 10pt;">&nbsp;registered with this email address. If this was not you, please ignore this email.</span></span></p>',
                
                'forgot_subject' => 'Request to reset your password',
                'forgot_email' => '<p><span style="color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, " segoe="" ui",="" roboto,="" oxygen,="" ubuntu,="" "fira="" sans",="" "droid="" "helvetica="" neue",="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" pre-wrap;"=""><span style="color: rgb(103, 106, 108);">Dear [USERNAME],</span></span></p><p><span style="color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, " segoe="" ui",="" roboto,="" oxygen,="" ubuntu,="" "fira="" sans",="" "droid="" "helvetica="" neue",="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" pre-wrap;"=""><span style="color: rgb(103, 106, 108);"><br></span>If you have forgotten your password, simply click on the button below to choose a set a new one.</span><br></p><p><br></p><p>[Button: link to reset]</p><p><br></p><p><span style="color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, " segoe="" ui",="" roboto,="" oxygen,="" ubuntu,="" "fira="" sans",="" "droid="" "helvetica="" neue",="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" pre-wrap;"="">Button not working? Paste the following link into your browser:</span></p><p><br></p><p>[text: link to reset]</p><p><br></p><p><span style="color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, " segoe="" ui",="" roboto,="" oxygen,="" ubuntu,="" "fira="" sans",="" "droid="" "helvetica="" neue",="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" pre-wrap;"="">You are receiving this email because you recently requested a reset password of the </span>[SITENAME]<span style="color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, " segoe="" ui",="" roboto,="" oxygen,="" ubuntu,="" "fira="" sans",="" "droid="" "helvetica="" neue",="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" pre-wrap;"=""> account registered with this email address. If this was not you, please ignore this email.</span></p>',
                
                'reset_subject' => 'Password Reset',
                'reset_email' => '<p style="margin: 0cm 0cm 7.5pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 10pt; font-family: " open="" sans",="" sans-serif;"=""><span style="font-size: 13px;">Dear [USERNAME],</span></span></p><p style="margin: 0cm 0cm 7.5pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 10pt; font-family: " open="" sans",="" sans-serif;"=""><span style="font-size: 13px;"><br></span>Your password is reset successfully.<o:p></o:p></span></p><p style="margin: 0cm 0cm 7.5pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 10pt; font-family: " open="" sans",="" sans-serif;"="">&nbsp;</span></p><p style="margin: 0cm 0cm 7.5pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;" helvetica="" ",="" helvetica,="" arial,="" "=""><span style="font-size:10.0pt;font-family:" open="" sans",sans-serif;color:#1d2228"="">Thank
                you for choosing&nbsp;</span><span open="" ",="" "helvetica="" helvetica,="" arial,="" "=""><span style="font-size: 10pt; font-family: " open="" sans",="" sans-serif;"="">[SITENAME]</span></span><span style="font-size:10.0pt;font-family:" open="" sans",sans-serif;color:#1d2228"="">!<o:p></o:p></span></p><p style="margin: 0cm 0cm 7.5pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;" helvetica="" ",="" helvetica,="" arial,="" "=""><span style="font-size:10.0pt;font-family:" open="" sans",sans-serif;color:#1d2228"="">-<br>
                The&nbsp;</span><span open="" ",="" "helvetica="" helvetica,="" arial,="" "=""><span style="font-size: 10pt; font-family: " open="" sans",="" sans-serif;"="">[SITENAME]&nbsp;</span></span><span style="font-size:10.0pt;font-family:" open="" sans",sans-serif;color:#1d2228"="">Team<o:p></o:p></span></p><p style="margin: 0cm 0cm 7.5pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-size: 10pt; font-family: " open="" sans",="" sans-serif;"="">&nbsp;</span></p><p></p><p style="margin: 0cm 0cm 7.5pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span segoe="" ",="" roboto,="" oxygen,="" ubuntu,="" "fira="" "droid="" "helvetica="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" "=""><span style="font-size:10.0pt;font-family:" open="" sans",sans-serif;color:#172b4d"="">You
                are receiving this email because you recently reset your password of the&nbsp;</span></span><span style="font-size: 10pt; font-family: " open="" sans",="" sans-serif;"="">[SITENAME]</span><span segoe="" ",="" roboto,="" oxygen,="" ubuntu,="" "fira="" "droid="" "helvetica="" sans-serif;="" font-size:="" 14px;="" letter-spacing:="" -0.07px;="" white-space:="" "=""><span style="font-size:10.0pt;font-family:" open="" sans",sans-serif;color:#172b4d"="">&nbsp;account
                registered with this email address. If this was not you, please ignore this
                email.</span></span><span style="font-size: 10pt; font-family: " open="" sans",="" sans-serif;"=""><o:p></o:p></span></p>',
                
                'request_subject' => 'New Booking: [Invited-Username] and [Requesting-Username] @ [DateTime]',
                'request_email' => '<h4 style="font-family: Arial, sans-serif; font-weight: normal; line-height: 1.4; color: rgb(0, 153, 0); margin: 0px 0px 4px; font-size: 13px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; padding: 6px 0px; border: 1px solid rgb(255, 255, 255);"><span style="font-weight: 700;">You have booked [Invited-Username] for the following date and time.</span></h4><div style="color: rgb(29, 34, 40); font-family: Arial, sans-serif; padding: 2px;"><span itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization"></span><h3 style="font-family: Arial, sans-serif; color: rgb(34, 34, 34); margin: 0px; padding: 0px 0px 6px;"><span itemprop="name">[Invited-Username] and [Requesting-Username]</span></h3><h3 style="font-family: Arial, sans-serif; color: rgb(34, 34, 34); margin: 0px; padding: 0px 0px 6px;"><span itemprop="name"><br></span></h3><table style="display: inline-table;" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="padding-right: 1em; padding-bottom: 10px; word-break: normal; color: rgb(136, 136, 136); white-space: nowrap; width: 90px;" valign="top">When&nbsp;</td><td style="padding-bottom: 10px; word-break: normal;" valign="top"><font color="#222222">[DateTime]</font></td></tr><tr><td style="padding-right: 1em; padding-bottom: 10px; word-break: normal; color: rgb(136, 136, 136); white-space: nowrap; width: 90px;" valign="top">Who</td><td style="padding-bottom: 10px; word-break: normal; color: rgb(34, 34, 34);" valign="top"><table cellspacing="0" cellpadding="0"><tbody><tr><td style="padding-right: 10px; word-break: normal;"><div style="margin: 0px 0px 0.3em;"><span itemprop="attendee" itemscope="" itemtype="http://schema.org/Person">[Invited-Username]</span><span itemprop="organizer" itemscope="" itemtype="http://schema.org/Person"></span><span style="font-size: 11px; color: rgb(136, 136, 136);">&nbsp;- organizer</span></div></td></tr><tr><td style="padding-right: 10px; word-break: normal;"><div style="margin: 0px 0px 0.3em;"><span itemprop="attendee" itemscope="" itemtype="http://schema.org/Person">[Requesting-Username]</span></div></td></tr></tbody></table></td></tr></tbody></table><div style="padding-bottom: 15px; color: rgb(34, 34, 34); overflow-wrap: break-word; white-space: pre-wrap !important;"><p><br></p><p>Powered by <span open="" sans",="" "helvetica="" neue",="" helvetica,="" arial,="" sans-serif;="" white-space:="" normal;"="" style="color: rgb(103, 106, 108);">[SITENAME]</span></p></div></div>',
                
                'booking_subject' => 'New Booking Invitation: [Invited-Username] and [Requesting-Username] @ [DateTime]',
                'booking_email' => '<h4 style="font-family: Arial, sans-serif; font-size: 13px; padding: 6px 0px; margin: 0px 0px 4px; line-height: 1.4; border: 1px solid rgb(255, 255, 255); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(0, 153, 0); font-weight: normal;"><strong>You have been booked by [Requesting-Username] for the following date and time.</strong></h4><div style="color: rgb(29, 34, 40); font-family: Arial, sans-serif; padding: 2px;"><span itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization"></span><h3 style="padding: 0px 0px 6px; margin: 0px; font-family: Arial, sans-serif; color: rgb(34, 34, 34);"><span itemprop="name">[Invited-Username] and [Requesting-Username] </span></h3><h3 style="padding: 0px 0px 6px; margin: 0px; font-family: Arial, sans-serif; color: rgb(34, 34, 34);"><span itemprop="name"><br></span></h3><table style="display: inline-table;" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="word-break: normal; padding-right: 1em; padding-bottom: 10px; color: rgb(136, 136, 136); white-space: nowrap; width: 90px;" valign="top">When</td><td style="word-break: normal; padding-bottom: 10px;" valign="top"><font color="#222222">[DateTime]</font></td></tr><tr><td style="word-break: normal; padding-right: 1em; padding-bottom: 10px; color: rgb(136, 136, 136); white-space: nowrap; width: 90px;" valign="top">Who</td><td style="word-break: normal; padding-bottom: 10px; color: rgb(34, 34, 34);" valign="top"><table cellspacing="0" cellpadding="0"><tbody><tr><td style="word-break: normal; padding-right: 10px;"><div style="margin: 0px 0px 0.3em;"><span itemprop="attendee" itemscope="" itemtype="http://schema.org/Person">[Invited-Username]</span><span itemprop="organizer" itemscope="" itemtype="http://schema.org/Person"></span><span style="font-size: 11px; color: rgb(136, 136, 136);">&nbsp;- organizer</span></div></td></tr><tr><td style="word-break: normal; padding-right: 10px;"><div style="margin: 0px 0px 0.3em;"><span itemprop="attendee" itemscope="" itemtype="http://schema.org/Person">[Requesting-Username]</span></div></td></tr></tbody></table></td></tr></tbody></table><div style="padding-bottom: 15px; color: rgb(34, 34, 34); overflow-wrap: break-word; white-space: pre-wrap !important;"><p><br></p><p>Powered by <span style="color: rgb(103, 106, 108); font-family: " open="" sans",="" "helvetica="" neue",="" helvetica,="" arial,="" sans-serif;="" white-space:="" normal;"="">[SITENAME]</span></p></div></div>',
                
                'cancel_subject' => 'Canceled Booking Invitation: [Username-1] and [Username-2] @ [DateTime]',
                'cancel_email' => '<h4 style="font-family: Arial, sans-serif; font-weight: normal; line-height: 1.4; color: rgb(0, 153, 0); margin: 0px 0px 4px; font-size: 13px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; padding: 6px 0px; border: 1px solid rgb(255, 255, 255);"><span style="font-weight: 700;">This event has been changed.</span></h4><div style="color: rgb(29, 34, 40); font-family: Arial, sans-serif; padding: 2px;"><span itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization"></span><h3 style="font-family: Arial, sans-serif; color: rgb(34, 34, 34); margin: 0px; padding: 0px 0px 6px;"><span itemprop="name">Canceled: [Username-1] and [Username-2]</span></h3><h3 style="font-family: Arial, sans-serif; color: rgb(34, 34, 34); margin: 0px; padding: 0px 0px 6px;"><span itemprop="name"><br></span></h3><table cellpadding="0" cellspacing="0" border="0" style="display: inline-table;"><tbody><tr><td valign="top" style="padding-right: 1em; padding-bottom: 10px; word-break: normal; color: rgb(136, 136, 136); white-space: nowrap; width: 90px;">When</td><td valign="top" style="padding-bottom: 10px; word-break: normal;"><font color="#222222">[DateTime]</font></td></tr><tr><td valign="top" style="padding-right: 1em; padding-bottom: 10px; word-break: normal; color: rgb(136, 136, 136); white-space: nowrap; width: 90px;">Who</td><td valign="top" style="padding-bottom: 10px; word-break: normal; color: rgb(34, 34, 34);"><table cellspacing="0" cellpadding="0"><tbody><tr><td style="padding-right: 10px; word-break: normal;"><div style="margin: 0px 0px 0.3em;"><span itemprop="attendee" itemscope="" itemtype="http://schema.org/Person">[Username-1]</span><span itemprop="organizer" itemscope="" itemtype="http://schema.org/Person"></span><span style="font-size: 11px; color: rgb(136, 136, 136);">&nbsp;- organizer</span></div></td></tr><tr><td style="padding-right: 10px; word-break: normal;"><div style="margin: 0px 0px 0.3em;"><span itemprop="attendee" itemscope="" itemtype="http://schema.org/Person">[Username-2]</span></div></td></tr></tbody></table></td></tr></tbody></table><div style="padding-bottom: 15px; color: rgb(34, 34, 34); overflow-wrap: break-word; white-space: pre-wrap !important;"><p><br></p><p>Powered by <span open="" sans",="" "helvetica="" neue",="" helvetica,="" arial,="" sans-serif;="" white-space:="" normal;"="" style="color: rgb(103, 106, 108);">[SITENAME]</span></p></div></div>',
                
                'reschedule_subject' => 'Updated Booking Invitation: [Username-1] and [Username-2] @ [DateTime]',
                'reschedule_email' => '<h4 style="font-family: Arial, sans-serif; font-size: 13px; padding: 6px 0px; margin: 0px 0px 4px; line-height: 1.4; border: 1px solid rgb(255, 255, 255); background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(0, 153, 0); font-weight: normal;"><strong>This event has been changed.</strong></h4><div style="color: rgb(29, 34, 40); font-family: Arial, sans-serif; padding: 2px;"><span itemprop="publisher" itemscope="" itemtype="http://schema.org/Organization"></span><h3 style="font-family: Arial, sans-serif; color: rgb(34, 34, 34); margin: 0px; padding: 0px 0px 6px;"><span itemprop="name">[Username-1] and [Username-2]</span></h3><h3 style="font-family: Arial, sans-serif; color: rgb(34, 34, 34); margin: 0px; padding: 0px 0px 6px;"><span itemprop="name"><br></span></h3><table cellpadding="0" cellspacing="0" border="0" style="display: inline-table;"><tbody><tr><td valign="top" style="padding-right: 1em; padding-bottom: 10px; word-break: normal; color: rgb(136, 136, 136); white-space: nowrap; width: 90px;">When</td><td valign="top" style="padding-bottom: 10px; word-break: normal;"><font color="#222222">[DateTime]</font></td></tr><tr><td valign="top" style="padding-right: 1em; padding-bottom: 10px; word-break: normal; color: rgb(136, 136, 136); white-space: nowrap; width: 90px;">Who</td><td valign="top" style="padding-bottom: 10px; word-break: normal; color: rgb(34, 34, 34);"><table cellspacing="0" cellpadding="0"><tbody><tr><td style="padding-right: 10px; word-break: normal;"><div style="margin: 0px 0px 0.3em;"><span itemprop="attendee" itemscope="" itemtype="http://schema.org/Person">[Username-1]</span><span itemprop="organizer" itemscope="" itemtype="http://schema.org/Person"></span><span style="font-size: 11px; color: rgb(136, 136, 136);">&nbsp;- organizer</span></div></td></tr><tr><td style="padding-right: 10px; word-break: normal;"><div style="margin: 0px 0px 0.3em;"><span itemprop="attendee" itemscope="" itemtype="http://schema.org/Person">[Username-2]</span></div></td></tr></tbody></table></td></tr></tbody></table><div style="padding-bottom: 15px; color: rgb(34, 34, 34); overflow-wrap: break-word; white-space: pre-wrap !important;"><p>Need to make changes to this event?<br>Cancel: [Cancel-Link]<br>Reschedule: [Reschedule-Link]</p><p>Powered by <span open="" sans",="" "helvetica="" neue",="" helvetica,="" arial,="" sans-serif;="" white-space:="" normal;"="" style="color: rgb(103, 106, 108);">[SITENAME]</span></p></div></div>',
                
                'inquire_event_subject' => 'Event Inquiry',
                'inquire_event_email' => '<p><font color="#172b4d">Dear [USER_NAME],</font></p><p><font color="#172b4d">You have got an inquiry against your event "[EVENT_TITLE]" on [SITENAME].</font></p><p><font color="#172b4d"><br></font></p><p><font color="#172b4d">Inquiry details are as follows:</font></p><p><font color="#172b4d">Inquiry Message : [INQUIRY]</font></p><p><font color="#172b4d">Inquired by [INQUIRY_USER_NAME]&nbsp;</font></p><p></p>',
                
                'created_by' => 1,
                'created_at' => now(),
            
            ],
        ]);
    }
}